### ISSUE TITLE
C#7: Local functions

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/csharp-tmLanguage#10]
Design document: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.0/local-functions.md

**Comment by DustinCampbell** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/2000 reports that the return type of local functions is not properly syntax highlighted. 

```C#
class C
{
    void M()
    {
        int TimesTen(int n) => n * 10;
        int a = 10;
    }
}
```

![image](https://user-images.githubusercontent.com/116161/35742941-ecb3f5fa-07f0-11e8-9f7e-89b75ceb362b.png)

**Comment by JoeRobich** [comment]
Cannot reproduce. Closing.
