### ISSUE TITLE
'in' parameters not highlighted correctly

### ISSUE THREAD

**Issue by MonaTheMonad** [dotnet/csharp-tmLanguage#102]
## Expectation

The keyword `in` should be highlighted blue like `ref` and `out` would be in the same location.

## Reality

It isn't. The type name following it isn't highlighted correctly, either.

## Reproduction

![screen shot 2018-03-04 at 15 36 34](https://user-images.githubusercontent.com/13571712/36950278-e1230ab2-1fc1-11e8-9014-ca02112a633e.png)

## Version

**Visual Studio Code - Insiders** version 1.21.0-insider

**Comment by DustinCampbell** [comment]
Thanks for the report!
