### ISSUE TITLE
theme local?

### ISSUE THREAD

**Issue by rakkarage** [dotnet/csharp-tmLanguage#103]
## Details

![2018_03_08](https://user-images.githubusercontent.com/962340/37190738-8e0bcede-2329-11e8-996f-c456242c4afa.png)

entity.name.variable.local.cs only modifies the color & style of locals when declared but not used?
thanks

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)

vscode

What version of the editor are you using?

latest insiders

What color theme are you using?

light+

## Repro

	"editor.tokenColorCustomizations": {
		"[Default Light+]": {
			"comments": "#ff0000",
			"textMateRules": [
				{
					"name": "variables",
					"scope": "entity.name.variable.local.cs",
					"settings": {
						"foreground": "#FF0000",
						"fontStyle": "bold"
					},
				}
			]
		},
	},

**Comment by rakkarage** [comment]
![text_mate1](https://user-images.githubusercontent.com/962340/37190828-1edcbe96-232a-11e8-8b4c-36e418d994bb.jpg)
![text_mate2](https://user-images.githubusercontent.com/962340/37190830-20874900-232a-11e8-8072-dae524eca191.jpg)

**Comment by DustinCampbell** [comment]
Unfortunately, there's no way to tell whether an identifier is a local variable (or a field, or a property, or a constant, etc.) without semantic analysis. TextMate grammars are simply a collection of regular expressions, so such semantic analysis can't be performed.

In VS Code, we hope that https://github.com/Microsoft/vscode/issues/585 will eventually provide an API to add semantic highlights, so we can add them from C# for VS Code. However, the TextMate grammar will never be able to do this.
