### ISSUE TITLE
Trailing null coalescing operator stops further syntax highlighting

### ISSUE THREAD

**Issue by Muchiachio** [dotnet/csharp-tmLanguage#107]
## Details
Visual Studio Code: 1.22.1 (Customized Monokai)

## Repro
```C#
using System.Linq;

namespace Test
{
    class Test
    {
        private object F()
        {
            return typeof(object).GetMember("null").FirstOrDefault()?.Name;
        }
        private object F1()
        {
            return typeof(object)
                .GetMember("null")
                .FirstOrDefault()? // ? breaks further highlighting
                .Name;
        }
        private void F2()
        {
        }
    }
}
```
![image](https://user-images.githubusercontent.com/6647444/38513128-ecc3fc1a-3c35-11e8-948b-80020ecbaa2b.png)

**Comment by kasper3** [comment]
can't seem to reproduce with latest VS Code and GitHub (`.Name` will not have different color, but if you call some method that will)

```c#
using System.Linq;

namespace Test
{
    class Test
    {
        private object F()
        {
            return typeof(object).GetMember("null").FirstOrDefault()?.Name;
        }
        private object F1()
        {
            return typeof(object)
                .GetMember("null")
                .FirstOrDefault()? // ? breaks further highlighting
                .Cast<object>()
                .Name;
        }
        private void F2()
        {
        }
    }
}
```

![image](https://user-images.githubusercontent.com/33230602/40020513-ed641e4c-57ca-11e8-88e3-4cf7cf502dd2.png)

**Comment by DustinCampbell** [comment]
It looks to me like you reproed it. It's just that you're using a different dark theme.

**Comment by Muchiachio** [comment]
Yes, even github syntax highlights break :smiley:

**Comment by kasper3** [comment]
ah, I am not sure what is the expected color :D

**Comment by kasper3** [comment]
Aha sorry for the noise, I was thinking the next `Cast<>` had an issue 😄

**Comment by Muchiachio** [comment]
Closing to reduce duplication in favor of #163.
