### ISSUE TITLE
Chained control and using statement breaks next method's highlighting

### ISSUE THREAD

**Issue by MonaTheMonad** [dotnet/csharp-tmLanguage#124]
## Details

Visual Studio Code 1.25.0-insider

I don't think this is a very high priority issue, as I don't think this is good style anyway.
Also, this bug arises when any such control statement is used, such as "while", and not only the example below.

## Repro

![image](https://user-images.githubusercontent.com/13571712/41570266-0e375cce-733c-11e8-83fa-9b8cc894e804.png)
![image](https://user-images.githubusercontent.com/13571712/41570305-328bf936-733c-11e8-946d-c2c46ec3de8d.png)

**Comment by DustinCampbell** [comment]
Good bug -- thanks!
