### ISSUE TITLE
Cast highlighted incorrectly in control structures

### ISSUE THREAD

**Issue by MonaTheMonad** [dotnet/csharp-tmLanguage#125]
## Details

Visual Studio Code (1.25.0-insider)

## Repro

![image](https://user-images.githubusercontent.com/13571712/41815551-815907b2-773c-11e8-891c-848cdc221fa8.png)
Also occurs in while loops, if statements, etc, and even when the lhs is not an indexer expression. Issue does not arise when the expression being cast is not a function call.
![image](https://user-images.githubusercontent.com/13571712/41815563-c6ab32ea-773c-11e8-9cd6-555dbbcca747.png)

**Comment by wise0704** [comment]
It seems already fixed in the main branch. Not sure which commit.

**Comment by JoeRobich** [comment]
Confirmed. Adding a test for good measure.
