### ISSUE TITLE
Pointer highlighting doesn't work

### ISSUE THREAD

**Issue by MonaTheMonad** [dotnet/csharp-tmLanguage#128]
## Details

Visual Studio Code (1.26.0-insider)

Pointer types (in declarations and cast expressions) are highlighted like the left side of a multiplication expression. That is, it's light blue like a variable.

## Repro

Declare pointers or cast to a pointer type.

**Comment by DustinCampbell** [comment]
Unfortunately, there's much that we can do here with regular expression-based rules. This situation is essentially ambiguous without a proper parser and we decided that multiplication expressions are more common that unsafe pointer types in C#. See https://github.com/dotnet/csharp-tmLanguage/issues/99

**Comment by MonaTheMonad** [comment]
Oh, okay. I might as well use the functions in the Marshal class, as I would not need to resort to using `unsafe` code.
