### ISSUE TITLE
C#7: 'switch' statement patterns

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/csharp-tmLanguage#13]
Design document: https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md

**Comment by garora** [comment]
> Design document: https://github.com/dotnet/roslyn/blob/post-dev15/docs/features/patterns.md

This url is not working, getting 404 error.

**Comment by DustinCampbell** [comment]
Updated. Thanks!
