### ISSUE TITLE
Feature request: syntax coloring improvement

### ISSUE THREAD

**Issue by akshita31** [dotnet/csharp-tmLanguage#148]
Please implement syntax coloring for **Properties**, **Variables**, **Enums**, **Parameter Names** and maybe for **Errors** too...

Here is the comparison between Visual Studio w/ ReSharper and VSCODE.

![image](https://user-images.githubusercontent.com/385958/51806681-cc2df900-224a-11e9-957a-20d86bffd82b.png)

![image](https://user-images.githubusercontent.com/385958/51807161-7c9efb80-2251-11e9-849a-56bba36c8b45.png)

_(Original request for color syntaxing https://github.com/OmniSharp/omnisharp-vscode/issues/674)_

**Comment by DustinCampbell** [comment]
Unfortunately, this isn't possible. TextMate grammars cannot perform highlighting that requires semantics.
