### ISSUE TITLE
Syntax highlighting stops without ;

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/csharp-tmLanguage#15]
_From @tverboon on January 27, 2017 7:12_

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

VS Code version: 1.8.1
C# Extension version: 1.7.0-beta1

## Steps to reproduce

```
namespace MyTest
{
    public class ColorTest
    {
        private readonly string _color
        public ColorTest(string white)
        {
            _color = white;
        }
    }
}
```

## Expected  behavior
This behavior happens when there is a syntax error (missing ;), so this makes it absolutely clear. Maybe it's a feature 😄 Visual Studio syntax highlighting continues to work for other lines, so I guess most users will expect that to be with VS Code also.

## Actual behavior
<img width="391" alt="screen shot 2017-01-27 at 08 01 07" src="https://cloud.githubusercontent.com/assets/6871049/22363000/62ca9cde-e467-11e6-8ce2-3da88d57105c.png">

Edit: It looks like that it only happens within class block and not in a method:
<img width="341" alt="screen shot 2017-01-27 at 13 57 16" src="https://cloud.githubusercontent.com/assets/6871049/22371661/95e18318-e498-11e6-959f-e271a63de342.png">

_Copied from original issue: OmniSharp/omnisharp-vscode#1152_

**Comment by DustinCampbell** [comment]
Note that VS continues to work because there's a proper parser doing the colorization in VS Code. In VS Code, this is much trickier because it's all done with regular expressions as part of a TextMate grammar. 😦

**Comment by tverboon** [comment]
Thanks! Will create issues like this in this repo next time.

Still waiting for this one, I guess 😉: https://github.com/Microsoft/vscode/issues/585

**Comment by DustinCampbell** [comment]
You can create issues in omnisharp-vscode repo too. This repo is new. The C# TextMate grammar is here so it can easily be shared among VS Code, Atom, VS, Sublime, etc.

Yes, we're definitely pushing for that.
