### ISSUE TITLE
C#8 Using Declarations not supported

### ISSUE THREAD

**Issue by erezwanderman** [dotnet/csharp-tmLanguage#156]
## Details
Code with the new [using declarations](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations) is not highlighted correctly.

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
Visual Studio Code

What version of the editor are you using?
1.35.1

What color theme are you using?
Monokai

## Repro

Please provide a code example and (optionally) a screenshot demonstrating the problem.
```
public class A
{
    public void B()
    {
        using (var keyServices = Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Services"))
        foreach (string serviceName in keyServices.GetSubKeyNames())
        {
            using var keyService = keyServices.OpenSubKey(serviceName);
        }
    }
}
```
![image](https://user-images.githubusercontent.com/6747955/60439463-9aff8d80-9c1b-11e9-91e1-ef198152da0e.png)

Expected results: the word "using" is colored like a keyword.
Actual results: it isn't.

**Comment by wise0704** [comment]
Seems fixed now:

https://github.com/dotnet/csharp-tmLanguage/blob/a99ed136d2305b29ce25270a7682ee181a532f1f/src/csharp.tmLanguage.yml#L1563-L1567

![image](https://github.com/dotnet/csharp-tmLanguage/assets/13545633/843ba6f1-406b-4a01-8d85-ab7b5375f1e9)

**Comment by JoeRobich** [comment]
Confirmed.
