### ISSUE TITLE
Syntax highlighting breaks for nullable arrays

### ISSUE THREAD

**Issue by stephtr** [dotnet/csharp-tmLanguage#157]
## Details

VS Code 1.36.1 (using theme Dark+)

## Repro
Syntax highlighting currently works for nullable objects, but not for nullable arrays. In the latter case syntax highlighting of the remaining file is broken.

```string[]? test = null;```

![image](https://user-images.githubusercontent.com/5764184/61622538-44fb9400-ac75-11e9-8475-efe3eb342bd0.png)

**Comment by 333fred** [comment]
Hit this one today.
