### ISSUE TITLE
C#8 interpolated verbatim strings get strange highlightings on github

### ISSUE THREAD

**Issue by bessgeor** [dotnet/csharp-tmLanguage#171]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
*GitHub*

As [stated](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) by GitHub, they use [Linguist](https://github.com/github/linguist) to detect code block language and highlight it.

As [stated](https://github.com/github/linguist/blob/master/vendor/README.md) by Linguist, they use [atom/language-csharp](https://github.com/atom/language-csharp) to do the highlighting.

As [stated](https://github.com/atom/language-csharp) by [atom/language-csharp](https://github.com/atom/language-csharp), they use grammar from this repo.

It seems to me that the bug is related to grammar, so I file the issue here. Feel free to correct me if the issue is not coming from this repo.

What version of the editor are you using?
*not appliable*

What color theme are you using?
*not appliable*

## Repro

From [my repo's readme](https://github.com/bessgeor/ZeroORM/blob/7cf0ab51ac05c33bdafa48a59db77d3736a0f881/readme.md),
```csharp
using System;
using Microsoft.EntityFrameworkCore;
using ZeroORM;

namespace ZeroORMExample
{
	class ExmpleClass
	{
		string GetLastCreatedItemIdSql(DbContext context)
			=> context
			.ZeroORM()
			.UseTable<ExampleEntityType>(out var exampleEntities)
			.Script()
			.RawSql(@$"
SELECT ""{exampleEntities.GetColumnName(e => e.Id)}""
FROM ""{exampleEntities.TableName}""
ORDER BY ""{exampleEntities.GetColumnName(e => e.CreatedAt)}"" DESC
LIMIT 1
"); // PostgreSQL SQL flavour
	}
}
```

The issue comes from usage of C#8' option to reorder string interpolation and verbatim markers. This conclusion was made because the issue does not reproduce with "classic" markers ordering:
```csharp
using System;
using Microsoft.EntityFrameworkCore;
using ZeroORM;

namespace ZeroORMExample
{
	class ExmpleClass
	{
		string GetLastCreatedItemIdSql(DbContext context)
			=> context
			.ZeroORM()
			.UseTable<ExampleEntityType>(out var exampleEntities)
			.Script()
			.RawSql($@"
SELECT ""{exampleEntities.GetColumnName(e => e.Id)}""
FROM ""{exampleEntities.TableName}""
ORDER BY ""{exampleEntities.GetColumnName(e => e.CreatedAt)}"" DESC
LIMIT 1
"); // PostgreSQL SQL flavour
	}
}
```

**Comment by bessgeor** [comment]
Would probably be fixed in https://github.com/dotnet/csharp-tmLanguage/pull/165/commits/f8163bba62b4eab81dab53a53456e92d74d5406d

**Comment by JoeRobich** [comment]
Confirmed fixed.
