### ISSUE TITLE
Field-like events with initializers

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/csharp-tmLanguage#18]
Events defined like the following example are not matched properly (admittedly, these are extremely rare)

```C#
class C
{
    public event Action E = () => { };
    public event Action E1 = () => { }, E2 = () => { };
}
```

**Comment by wise0704** [comment]
Should be fixed by #266

https://github.com/dotnet/csharp-tmLanguage/blob/a99ed136d2305b29ce25270a7682ee181a532f1f/test/event.tests.ts#L310-L315

@JoeRobich
