### ISSUE TITLE
await incorrectly highlighted in csx

### ISSUE THREAD

**Issue by dave-yotta** [dotnet/csharp-tmLanguage#181]
## Details

VSCode 1.45.1 Dark

## Repro

![image](https://user-images.githubusercontent.com/41444963/83531499-f77ec300-a4e4-11ea-865c-6e737763bc30.png)

See the last line - anything await (and anything following it) in the global scope of a c# script is not highlighted correctly. It's ok within a class method near top.

**Comment by JoeRobich** [comment]
Unable to reproduce with 1.82.0-insider

<img width="1418" alt="image" src="https://github.com/dotnet/csharp-tmLanguage/assets/611219/3573225f-2c77-4308-9713-03e427ffeeb3">
