### ISSUE TITLE
Grammar breaks when ? syntactic sugar is at the end of a line

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#183]
Originally from @lzw5399 in https://github.com/microsoft/vscode/issues/102572

## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code
What version of the editor are you using?
1.47.3 and 1.48
What color theme are you using?
N/A
## Repro

Please provide a code example and (optionally) a screenshot demonstrating the problem.
```csharp
using System.Threading.Tasks;
using System;
public class Example
{
    public async Task<string> Ok(string param)
    {
        return await Task.Run(() => "ok");
    }

    public void Method1()
    {
        var list = new List<string>();
        var filteredList = list? // <=
        .Where(it => it.Length > 3)
        .ToList();
    }

    public async Task<string> Error(string param)
    {
        return await Task.Run(() => "error");
    }
}
```

https://camo.githubusercontent.com/a4da2debadfd510d0475d0c00c9ad14831814b88/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303753385a496c6779316767726e377173316f6e6a33307568306a7174626f2e6a7067

**Comment by berdon** [comment]
Fwiw, this is also an issue for multi-line statements that contain ?; for example:

```c#
public Task Something()
{
    (DocumentType? documentType,
                    Guid? documentId,
                    MediaType? mediaType,
                    string fileExtension,
                    byte[] encryptionKey,
                    byte[] md5Checksum,
                    string description,
                    string comments) = request.AsTuple();
    // ...
}

public Task AnotherThing() { }
```

Though, one oddity, syntax highlighting still _mostly_ works within methods. But it's broken outside of methods.

**Comment by wise0704** [comment]
It seems impossible to fix. There's no way to differentiate between ?. and ? : if ? alone is at the end of the line. The context for both are also the same. `list?` could be followed with the line `.Where()`, but also `0 : 1`.

**Comment by wise0704** [comment]
> Fwiw, this is also an issue for multi-line statements that contain ?; for example:
> 
> ```cs
> public Task Something()
> {
>     (DocumentType? param1,
>                     Guid? param2,
>                     MediaType? param3,
>                     string param4,
>                     byte[] param5,
>                     byte[] param6,
>                     string param7,
>                     string param8) = request.AsTuple();
>     // ...
> }
> 
> public Task AnotherThing() { }
> ```
> 
> Though, one oddity, syntax highlighting still _mostly_ works within methods. But it's broken outside of methods.

This is a separate issue. Specifically
- var tuple deconstruction on multiple lines (`local-tuple-var-deconstruction`)
- tuple deconstruction on multiple lines (`tuple-deconstruction-assignment`)
