### ISSUE TITLE
Switch keyword in switch expression has incorrect scope

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#184]
Originally from @marlongerson  in https://github.com/microsoft/vscode/issues/103423

## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code
What version of the editor are you using?
1.47.2, 1.48
What color theme are you using?
N/A

## Repro

```c#
public enum Foo
{
    Bar,
    Baz,
}

public class A
{
    public int B(Foo foo) =>
        foo switch
        {
            Foo.Bar => 0,
            Foo.Baz => 1,
        };
}
```

1. Create switch expression
2. Notice that switch keyword is not syntax highlighted.

![image](https://camo.githubusercontent.com/3a35e04233435470971305a70abc30ebdd868fe4/68747470733a2f2f692e696d6775722e636f6d2f30445468455a6e2e706e67)

**Comment by wise0704** [comment]
Already handled in `switch-expression`
![image](https://github.com/dotnet/csharp-tmLanguage/assets/13545633/dfb28345-2afa-4e79-99af-cae1f07fc125)

**Comment by JoeRobich** [comment]
Confirmed.
