### ISSUE TITLE
C# Syntax highligting in razor files incorrect for nullable properties

### ISSUE THREAD

**Issue by tn-5** [dotnet/csharp-tmLanguage#191]
When defining a nullable property in the @code block in a razor file the syntax highlighting does not work correctly.

Details copied from: https://github.com/dotnet/aspnetcore/issues/24791

### Reproduce
* Generate standard template project: `dotnet new blazorserver`
* Open in VS Code
* Open FetchData.razor
* Observe syntax highlighting correctly highlights `WeatherForecast` as a class/type

### Add nullable field
* Add `string? test;` before the `WeatherForecast` declaration
* Observe that the highlighting of `WeatherForecast` is still correct

### Add nullable property
* Add `string? test1 {get; set;}` before the `WeatherForecast` declaration
* Observe that the highlighting of `WeatherForecast`now reverts to generic text

It does not seem to make any difference if the <nullable> setting on the project file is enabled or not.

**Comment by davidwengier** [comment]
This was fixed by https://github.com/dotnet/razor-tooling/pull/7019

Feed free to close :)
