### ISSUE TITLE
Records highlighting is not supported

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharp-tmLanguage#202]
See https://github.com/OmniSharp/omnisharp-vscode/issues/4211#issuecomment-821195798

It should support the different ways like the following:

```csharp
record R1;

record R2();

record R3() { }

record R4 { }
```

**Comment by JoeRobich** [comment]
partially fixed in #211

**Comment by Shadowblitz16** [comment]
I'm on kde neon 20.04 and I still get this issue with vscode
