### ISSUE TITLE
new keyword and constructor name are highlighted incorrectly

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#209]
From @mpearson in https://github.com/microsoft/vscode/issues/123333

## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code

What version of the editor are you using?
1.56

What color theme are you using?
N/A

## Repro

The new keyword and constructor name are highlighted incorrectly when a variable is assigned after being declared. When assigned and declared in the same statement, highlighting is correct. The scope inspector reveals that the new keyword is interpreted differently in these two situations.

```cs
using System.Collections.Generic;

class TestClass
{

    public List<int> ListField;

    public void TestMethod()
    {
        ListField = new List<int>();            // wrong
        
        List<int> localVar;
        localVar = new List<int>();             // wrong

        List<int> localVar2 = new List<int>();  // right
    }
}
```
Edit: looks like the grammar that github uses has a similar issue.

![image](https://user-images.githubusercontent.com/38270282/117664250-dd903a80-b1a1-11eb-84f4-a9955e30a470.png)

**Comment by JoeRobich** [comment]
Should be resolved with https://github.com/dotnet/csharp-tmLanguage/pull/212
