### ISSUE TITLE
Grammar now classifies `new` as `storage.type.cs` instead of `keyword.other.new.cs`

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#210]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code

What version of the editor are you using?
I'm a developer on VS Code. I updated the grammars today, and noticed in our tests that the latest grammar from dotnet/csharp-tmLanguage changes the scopes that `new` gets.

What color theme are you using?
N/A

## Repro

Please provide a code example and (optionally) a screenshot demonstrating the problem.
This is the sample we test with. The new in `new List` is getting the alternate scope. 
```cs
using System;
namespace SampleNamespace
{
    class TestClass
    {
        static void Main(string[] args)
        {
            int[] radii = { 15, 32, 108, 74, 9 };
            const double pi = 3.14159;
            foreach (int radius in radii) {
                double circumference = pi * (2 * radius);
                // Display the number of command line arguments:
                System.Console.WriteLine("Circumference = {0:N2}", circumference);
            }
        }

        public void TestMethod()
        {
            ListField = new List<int>();

            List<int> localVar;
            localVar = new List<int>();

            List<int> localVar2 = new List<int>();
        }
    }
}
```

Is this new scope intended? With VS Code's default themes, it results in `new` getting a different color, so I wanted to make sure this is intended before we start using the latest grammar.

**Comment by kasperk81** [comment]
```c#
var x = new object();
x = new object();
```

I think the color of type `object()` on RHS should match on both lines.

**Comment by alexr00** [comment]
@JoeRobich and @rchowe (since you have most recently changed the grammar), just FYI, this issue has once again prevented me from pulling the latest C# grammar into VS Code.

**Comment by JoeRobich** [comment]
@alexr00 Thanks for pinging me on this. I have opened a PR (https://github.com/dotnet/csharp-tmLanguage/pull/212) to resolve this issue.

**Comment by alexr00** [comment]
Thanks for making a fix! I have pulled the latest grammar into VS Code.
