### ISSUE TITLE
C# 10 File-scoped namespace declaration syntax coloring bug

### ISSUE THREAD

**Issue by edsulaiman** [dotnet/csharp-tmLanguage#229]
## Details

What editor are you seeing the problem in?
Visual Studio Code

What version of the editor are you using?
Version: 1.62.2 (system setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

What color theme are you using?
Atom One Dark

## Repro
1. Write a class using C# 10 [File-scoped namespace declaration](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration)

namespace with braces
![image](https://user-images.githubusercontent.com/52323183/141461342-9f78fbee-fc52-4c04-a13c-5416e401fe50.png)

namespace without braces
![image](https://user-images.githubusercontent.com/52323183/141461378-7c0a6670-7f90-4a44-b1ce-6d5f0e536017.png)

**Comment by JoeRobich** [comment]
GitHub also uses this grammar for highlighting. It appears that this issue was resolved when https://github.com/dotnet/csharp-tmLanguage/pull/253 merged. Closing

```csharp
using Microsoft.AspNetCore.MC;

namespace SomeProgram.Controllers;

[Route("some-class")]
public class Someclass: ControllerBase
{
    [HttpGet]
    public ActionResult Get()
    {
        return new OkResult();
    }
}
```
