### ISSUE TITLE
Incorrect Syntax Highlighting for Integer Extension Methods

### ISSUE THREAD

**Issue by PixelatedLagg** [dotnet/csharp-tmLanguage#231]
## Details

Visual Studio Code

1.62.2

One Monokai 80s Plus

## Repro
![image](https://user-images.githubusercontent.com/81400034/142063320-0cae1f49-8c39-46eb-9580-2789cec12367.png)

In the screenshot, an extension method I made for a string and integer are invoked, however the string highlights the method, while the integer doesn't. I am assuming the syntax highlighter thinks I am creating a numerical value with a decimal point and an invalid word afterwards, hence the white.

**Comment by wise0704** [comment]
Seems fixed.
![image](https://github.com/dotnet/csharp-tmLanguage/assets/13545633/93863583-7f7b-44b7-ac01-09d6cee39679)
