### ISSUE TITLE
Type names are classified as storage.type instead of entity.name.type

### ISSUE THREAD

**Issue by chtenb** [dotnet/csharp-tmLanguage#234]
## Details

What editor are you seeing the problem in? VSCode

## The problem

Referenced typenames are classified as `storage.type`. However, I noticed that this causes incoherent highlighting in many colorschemes, since I believe the guidelines say that `storage.type` are for things like `class` and `struct`. A typename would be classified by `entity.name.type{.class}`.

Is this a conscious decision? If not I'd willing to provide a PR to change this.

![image](https://user-images.githubusercontent.com/1030961/149375800-34c705b1-8de9-4e29-996e-5927108bbc93.png)

**Comment by JoeRobich** [comment]
From reviewing the documentation at https://macromates.com/manual/en/language_grammars#naming_conventions, I agree that this is a bug and we would welcome a PR for this. Thanks!
