### ISSUE TITLE
Attribute with string parameter breaks highlighting

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/csharp-tmLanguage#236]
Originally reported at https://github.com/OmniSharp/omnisharp-vscode/issues/5049

Issue Type: <b>Bug</b>

I have created a record. When adding ErrorMessage with string in attribute, there was a problem with highlighting.

![image](https://user-images.githubusercontent.com/18312706/153222069-267776a0-cbfa-42ac-8886-af0e73783b27.png)

```csharp
    public record BankInformation(
        string InformationId,
        string SalaryId,
        string BankName,
        [StringLength(34, ErrorMessage = "The IBAN {0} must not exceed {1} characters.")]
        string Iban,
        [StringLength(11, ErrorMessage = "The BIC code {0} must not exceed {1} characters.")]
        string Bic,
        string? AccountHolder,
        DateTime DateAdded
    );
```

**Comment by wise0704** [comment]
Cannot reproduce:
![image](https://github.com/dotnet/csharp-tmLanguage/assets/13545633/04584f3f-8272-412e-b1e3-6b96c342ebe9)

Probably fixed?

**Comment by JoeRobich** [comment]
Closing as I can no longer reproduce the issue.
