### ISSUE TITLE
C# syntax highlight is broken with slashes and await

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#241]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code

What version of the editor are you using?
1.66.1

What color theme are you using?
N/A

## Repro

```csharp
var httpClient = new HttpClient();
await httpClient.GetAsync($"https://localhost:7205");
```

See attached GIF. If function argument string contains two slashes and the function is awaited, so the syntax hlightlight is broken. This issue is reproduced both when OmniSharp is enabled or disabled.

![example](https://user-images.githubusercontent.com/22894169/162840130-f74a0649-270e-4dae-94ba-b5dc4f8d4cf5.gif)

Originally from @Igorgro in https://github.com/microsoft/vscode/issues/147258

**Comment by wise0704** [comment]
Seems fixed?

![image](https://github.com/dotnet/csharp-tmLanguage/assets/13545633/b1da4ae8-e844-442b-afdf-815caa33e539)

**Comment by mxschmitt** [comment]
I can confirm https://github.com/microsoft/vscode/issues/172508 is fixed now.
