### ISSUE TITLE
Support raw string literals

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/csharp-tmLanguage#243]
## Details

Observed with github.com's syntax highlighting of `c#` code blocks when using raw string literals from C# 10.

https://github.com/dotnet/csharplang/blob/main/proposals/raw-string-literal.md

## Repro

```c#
var s = """
    Hello, world!
    """;
```

The preview for this looks like:

![image](https://user-images.githubusercontent.com/350947/167975845-5b3e66c1-431d-4186-8def-a6a6ddd14327.png)

**Comment by 333fred** [comment]
This was implemented with https://github.com/dotnet/csharp-tmLanguage/pull/246.
