### ISSUE TITLE
Method call on numeric literal in C# marked as illegal

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#244]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code

What version of the editor are you using?
1.68 

What color theme are you using?
N/A

## Repro

Issue Type: <b>Bug</b>

Create a .cs file with the following content:
```cs
Console.WriteLine(1.23.ToString("0.000"));
```
The .ToString Method call will be marked as illegal even though this code compiles and runs without warnings.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/7098860/170383480-529193e8-cb0d-4918-9035-5f052c4cc63a.png">

Originally by @aliceif in https://github.com/microsoft/vscode/issues/150421

**Comment by nathanielboucher** [comment]
I believe this is a VSCode specific issue with OmniSharp, not a VSCode-specific issue. It seems to run fine with csc.

**Comment by 333fred** [comment]
> I believe this is a VSCode specific issue with OmniSharp, not a VSCode-specific issue. It seems to run fine with csc.

No. This is an issue with the grammar contained in this repository. If you were to turn on semantic highlighting in vscode, then this would go away, as O# would be providing the real token information.

**Comment by 333fred** [comment]
> I believe the O# analyzer is in fact wrong for this.

There is no O# analyzer. This repository contains the tmLanguage definition used by VSCode (and other textmate highlighters) when semantic info is not available. You can see this by looking at the token information given in the screenshot: it does not list any semantic scopes, only textmate scopes.

**Comment by nathanielboucher** [comment]
@333fred Thanks for the clarification! I got really confused myself from following this issue elsewhere. 

VSCode isn't my forte either. But, this highlighting is still icky.

**Comment by aliceif** [comment]
It has been an entire release of the C# language spec later and nothing has been done about this, is it possible to expect a fix to this issue that affects tools like Visual Studio Code and even GitHub itself as seen in the issue description?
