### ISSUE TITLE
Semantic token type of preserved keywords should be removed or better classified

### ISSUE THREAD

**Issue by UPIMMUNITY** [dotnet/csharp-tmLanguage#251]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
Visual Studio Code
What version of the editor are you using?
1.74.1
What color theme are you using?

## Repro
For example, semantic token type of primitive keywords is `plainKeyword`, those preserved keywords should not have semantic type, or it will destruct flexibility of customizing colorization between access modifiers and primitive types and so on. As far as I can tell, for preserved keywords, using textmate scope for them is just fine.

If I want to separately colorize access modifier and primitive types, this cannot be done when semanticHighlighting is enabled because their semantic token type are all the same(`plainKeyword`)!

In typescript, primitive keywords have no semantic token type and their colors works fine.

So please remove those semantic token type of preserved keywords, or assign different types to them.

**Comment by wise0704** [comment]
Tracked here: https://github.com/dotnet/vscode-csharp/issues/5993
