### ISSUE TITLE
File scope access modifier has wrong textmate scope

### ISSUE THREAD

**Issue by UPIMMUNITY** [dotnet/csharp-tmLanguage#252]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
Visual Studio Code
What version of the editor are you using?
1.74.1
What color theme are you using?
Eva Theme
## Repro
It's now a variable
![image](https://user-images.githubusercontent.com/77432836/208232569-8e6c8ad6-eff6-4641-92c4-5d4fe276bfb5.png)

**Comment by wise0704** [comment]
@JoeRobich should be fixed with #255?

**Comment by JoeRobich** [comment]
@wise0704 It should. Thanks for catching it.
