### ISSUE TITLE
`using` scope change

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#290]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code

What version of the editor are you using?
1.81

What color theme are you using?
Default, Dark Modern

## Repro

```
using System;
namespace SampleNamespace
{
    class TestClass
    {
        static void Main(string[] args)
        {
            int[] radii = { 15, 32, 108, 74, 9 };
            const double pi = 3.14159;
            foreach (int radius in radii) {
                double circumference = pi * (2 * radius);
                // Display the number of command line arguments:
                System.Console.WriteLine("Circumference = {0:N2}", circumference);
            }
        }

        public void TestMethod()
        {
            ListField = new List<int>();

            List<int> localVar;
            localVar = new List<int>();

            List<int> localVar2 = new List<int>();
        }
    }
}
```
Current syntax highlighting in VS Code
<img width="586" alt="image" src="https://github.com/dotnet/csharp-tmLanguage/assets/38270282/96a0405c-840f-47ec-9aa2-6eb8b906dcf9">

If I were to pull in the latest changes from https://github.com/dotnet/csharp-tmLanguage
<img width="536" alt="image" src="https://github.com/dotnet/csharp-tmLanguage/assets/38270282/b0c5d69a-811a-480e-88c3-f1f341f2fcf8">

The scope assigned to `using` has gone from `keyword.other.using.cs` to `keyword.other.directive.using.cs`. Is this intentional?

**Comment by JoeRobich** [comment]
@alexr00 Thanks for pointing this out. We did intentionally update many of our scopes to be more specific. We grouped many keywords beneath broad categories. I see now that the VS Code themes are expecting `keyword.other.using` and that the cpp tmLanguage uses `keyword.other.using.directive` to provide this extra detail.

**Comment by wise0704** [comment]
Should the directive keywords (`using`, `static`, `global`, `extern alias`) then have the scope `keyword.other.X.directive` instead?
In terms of grouping it makes less sense, but it will be compatible with the existing configuration.

But it will be harder to configure all the directive keywords into one colour, as you will then have to configure them individually (unless something like `keyword.other.*.directive` works? I've never tried).

**Comment by alexr00** [comment]
Thanks @JoeRobich! I will update the VS Code themes.
