### ISSUE TITLE
Grammar breaks after less-than check when not surrounded by parentheses 

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#295]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)

VS Code

What version of the editor are you using?

1.83, which has commit `525e628edad54c0f7aa15b015310df240803ea66` from this repo

What color theme are you using?

Issue occurs regardless of color theme

## Repro

![image](https://github.com/dotnet/csharp-tmLanguage/assets/38270282/36fb563a-5f5b-4903-b248-446fba8a1f66)

```csharp
    public void nextPage()
    {
        if (!setPage(tabs[currentTab].currentPage + 1))
        {
            int lastTab = tabs.Length - 1;
            if (currentTab < lastTab && setTabWithoutUpdate(currentTab + 1))
            {
                if (!setPage(0))
                    updateItems();
            }
        }
    }
    public void prevPage()
    {
        if (!setPage(tabs[currentTab].currentPage - 1))
        {
            if (currentTab > 0 && setTabWithoutUpdate(currentTab - 1))
            {
                int lastPage = Math.Max(currentItems.Count - 1, 0) / 6;
                if (!setPage(lastPage))
                    updateItems();
            }
        }
    }
```

Line `currentTab < lastTab && setTabWithoutUpdate(currentTab + 1)` is not parsed correctly and syntax highlighting breaks after it. Adding useless brackets around `(currentTab < lastTab)` fixes this particular issue but there are other issues. Highlight for certain keywords changed for no reason (such as `class`, `var`, etc.). This happens with and without extensions enabled, this is purely base syntax highlighting built into VS Code. 

Originally posted by @DemonikGH in https://github.com/microsoft/vscode/issues/195098

**Comment by alexr00** [comment]
👋 I manage pulling updates from dotnet/csharp-tmLanguage to microsoft/vscode for the C# grammar. For now, I'm going to set VS Code back to use commit `772323937fedd65c6dc1c8ce6ea41d97415ed7d1`, which was the last version we released with that didn't have this issue.

**Comment by wise0704** [comment]
I suspect #273 is causing this regression.

**Comment by wise0704** [comment]
> ... Highlight for certain keywords changed for no reason (such as `class`, `var`, etc.). This happens with and without extensions enabled, this is purely base syntax highlighting built into VS Code.

This is unrelated.
Keyword scopes have been changed to follow the standards/conventions, and are thus compatible with existing themes.
Refer to 

* #281 
* #278 

for the detailed changes.
