### ISSUE TITLE
[Textmate] `nameof` in const Interpolated string

### ISSUE THREAD

**Issue by sharpchen** [dotnet/csharp-tmLanguage#305]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
vscode
What version of the editor are you using?
1.85.1
What color theme are you using?
dark plus
## Repro
```cs
[HttpGet($"{{{nameof(id)}}}")]
public async Task<ActionResult<ServiceResponse<Product>>> Get(int id)
{
    var product = await _service.GetProductAsync(id);
    return Ok(product);
}

[Attribute($"{nameof(obj)}")]
[Attribute($"{{nameof(obj)}}")]
[Attribute($"{{{nameof(obj)}}}")]
static void M(object obj) { }

class AttributeAttribute : Attribute{
    private string S { get; set; }
    public AttributeAttribute(string s) => S = s;
}
```
![image](https://github.com/dotnet/csharp-tmLanguage/assets/77432836/93c759e9-907f-4ee1-964e-0c1bb7228f5a)

Please provide a code example and (optionally) a screenshot demonstrating the problem.

**Comment by sharpchen** [comment]
Can't reproduce earlier example. Currently is 
![image](https://github.com/dotnet/csharp-tmLanguage/assets/77432836/c5375e0e-c74c-4559-973b-454693d14464)
```cs
[Attribute($"{{nameof(obj)}}")]
static void M(object obj) { }

class AttributeAttribute : Attribute {
    private string S { get; set; }
    public AttributeAttribute(string s) => S = s;
}
```

**Comment by JoeRobich** [comment]
> To test textmate colors, should I enable C# related extension?

The C# grammar ships separate from the C# extension, so if you have the C# extension uninstalled or disabled then that is fine. If the C# extension is installed and enabled, then you would want to be sure to disable semantic highlighting in your settings.

Also, there is a handy 'Inspect Tokens' command that you can invoke which will give you details about how the token at the current cursor position is classified.

**Comment by sharpchen** [comment]
I put my code in markdown code block, so vscode will use textmate rules only to color them, am I doing it right? But when I enable C# related extensions, colorization may change a bit. The earlier example is captured when extensions disabled.

**Comment by JoeRobich** [comment]
Easiest just to set `editor.semanticHighlight.enable` to `false` while you are doing your testing. You could even make a separate profile just for textmate testing. Then the C# extension could be enabled or not.

**Comment by JoeRobich** [comment]
@sharpchen Is there a bug here? Like you, I cannot reproduce the issue you initially posted.


![Image](https://github.com/dotnet/csharp-tmLanguage/assets/611219/8541f29c-f423-49d6-80a6-8a6c7863a02c)

**Comment by JoeRobich** [comment]
I also wanted to say thank you for all the bugs that you've logged.

**Comment by sharpchen** [comment]
My bad, the initial example was tested in markdown block. However, vscode mis-recognize some part of the code as typescript(when C# related extensions are disabled), so I think here should be no bug. 
![image](https://github.com/dotnet/csharp-tmLanguage/assets/77432836/9100cb4a-e0be-4efb-9967-7b5d0217f700)

It's my pleasure, thank you for maintaining this repo!
