### ISSUE TITLE
csharp.tmLanguage: invalid pattern in look-behind

### ISSUE THREAD

**Issue by sebthom** [dotnet/csharp-tmLanguage#315]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
Ruby, [Eclipse TM4E](https://github.com/eclipse/tm4e/)

What version of the editor are you using?
0.9

What color theme are you using?
Solarized

## Repro

TextMate uses the [oniguruma syntax](https://macromates.com/manual/en/regular_expressions#syntax_oniguruma) for regular expressions.

The `await-statement` pattern at
https://github.com/dotnet/csharp-tmLanguage/blob/7a7482ffc72a6677a87eb1ed76005593a4f7f131/grammars/csharp.tmLanguage#L2939-L2942
however is not parsable using the oniguruma regex library and results in `invalid pattern in look-behind`.

you can try it here https://onecompiler.com/ruby/422uzf35h  Ruby uses the oniguruma library for regex parsing.

**Comment by sebthom** [comment]
I think the issue is the usage of variable-length negative look-behind. 

It might be easily solvable by changing:

```
from: /(?<!\.\s*)\b(await)\b/
  to: /(?<!\.)\s*\b(await)\b/
```

i.e.
```
from: <string>(?&lt;!\.\s*)\b(await)\b</string> 
  to: <string>(?&lt;!\.)\s*\b(await)\b</string> 
```

**Comment by RedCMD** [comment]
Ruby, Eclipse TM4E must be using an outdated version of oniguruma
as the current version of [oniguruma](https://github.com/kkos/oniguruma) does support variable length lookbehinds

**Comment by sebthom** [comment]
Yeah we are using the implementation from JRuby which apparently lags behind. Thanks for your pointer.
