### ISSUE TITLE
Problem with indexing an indexer expression

### ISSUE THREAD

**Issue by nomenon** [dotnet/csharp-tmLanguage#37]
VS Code 1.9.1
Color Theme: Dark+
C# 1.7.0

Highlight problem:
![1](https://cloud.githubusercontent.com/assets/16668962/22833832/edd92750-efbb-11e6-9f65-700341679819.png)

**Comment by DustinCampbell** [comment]
Thanks for the report! Note that the last example is also broken because the final `AsLong` is not highlighted properly.
