### ISSUE TITLE
Can we directly consume csharp.tmLanguage from source?

### ISSUE THREAD

**Issue by mickaelistria** [dotnet/csharp-tmLanguage#43]
The documentation seems to imply that a build is necessary to get the grammar. However, the repo contains https://github.com/dotnet/csharp-tmLanguage/blob/master/grammars/csharp.tmLanguage which seems legit.
Is it safe to directly consume the grammar from source repo (like a "binary" distribution) or is the build a mandatory step for consumers?

**Comment by DustinCampbell** [comment]
The grammars folder is updated with each PR, so you shouldn't need to build. When we get CI rolling, it'll ensure that the grammars folder is always updated. However, you should be able to trust it. VS Code is doing the same thing.

**Comment by DustinCampbell** [comment]
Let me know if you have anymore questions.

**Comment by mickaelistria** [comment]
Thanks, your answer was helpful and allowed to properly fix https://github.com/mickaelistria/aCute/issues/5

**Comment by DustinCampbell** [comment]
Great!
