### ISSUE TITLE
C#7: Expression-bodied accessors

### ISSUE THREAD

**Issue by CnSimonChan** [dotnet/csharp-tmLanguage#44]
## Details

VSCode 1.10.0-Insider

omnisharp-vscode 1.8.0-beta1

Dark+ (default dark) theme from VSCode

## Repro

1. The body of expression bodied properties doesn't have any color:

```` C#

public int Timeout
{
    get => Socket.ReceiveTimeout;
    set => Socket.ReceiveTimeout = value;
}

````

![1](https://cloud.githubusercontent.com/assets/1330321/23207705/2cc2ddd8-f92d-11e6-914d-c224f5d3e0cb.PNG)

2. `throw` keyword is treated as a variable in expression bodied method:

```` C#

public void Method() => throw new Exception();

````

![2](https://cloud.githubusercontent.com/assets/1330321/23207798/8abd4c48-f92d-11e6-9408-35f2a221461c.PNG)

**Comment by DustinCampbell** [comment]
Thanks for reporting this issue! This new C# 7 feature simply hasn't been implemented yet. Adding to the backlog.
