### ISSUE TITLE
DOTween method problem

### ISSUE THREAD

**Issue by nomenon** [dotnet/csharp-tmLanguage#45]
VS Code 1.9.1
Color Theme: Nord
C# 1.8.0-beta1 

```C#
void CandleLightOffSecond(int index)
{
    DOTween.ToAlpha(() => FSItems[index].CandleSecond.startColor, (x) => FSItems[index].CandleSecond.startColor = x, 0f, 1f).OnComplete(() => DisableCandleFX(index));
    DOTween.ToAlpha(() => FSItems[index].CandleSecond.startColor, (x) => FSItems[index].CandleSecond.startColor = x, 0f, 1f);
}
```

![default](https://cloud.githubusercontent.com/assets/16668962/23376953/bfb84008-fd36-11e6-8069-0533e39451ce.png)

**Comment by DustinCampbell** [comment]
Thanks for the report!

**Comment by nomenon** [comment]
@DustinCampbell Problem still exist in 1.9.0-beta2-private
![default](https://cloud.githubusercontent.com/assets/16668962/25039324/aa44ca54-210b-11e7-9f3d-f207f0c87086.png)

**Comment by DustinCampbell** [comment]
Looks like a different problem. Could you please file a separate issue?

**Comment by nomenon** [comment]
@DustinCampbell 
using UnityEngine;
using DG.Tweening;

public class BGController : MonoBehaviour
{
    [SerializeField] GameObject[] CoinsFX;
    [SerializeField] Transform[] CoinsFlying;

    private enum Coins
    {
        Collect = 0, Flying = 1, Start = 2, FlyingStart = 0, FlyingEndUp = 1, FlyingEndDown = 2
    }

    private void OnWheelStoppedHandler()
    {
        CoinsFX[(int)Coins.Start].SetActive(true);
        CoinsFX[(int)Coins.Flying].transform.DOMove(CoinsFlying[(int)Coins.FlyingEndDown].position, 1).OnComplete(() => { });
    }

    private void SetSectorsAfterRoll()
    {
    }
}
