### ISSUE TITLE
Is there a default theme that uses all these scopes?

### ISSUE THREAD

**Issue by eppz** [dotnet/csharp-tmLanguage#55]
Hi, just please help with some clarifications.

1. Is this TextMate gammar is currently ships with Visual Studio Code?

2. I'm making a theme, is there a documentation / list for all the scopes?
Or a default theme that uses all these scopes?

3. Does OmniSharp have any additional syntax highlighting method?
Something that uses code inspection instead regular expression matching.
That could differentiate e.g. a namespace from a class even if they have the same name.

**Comment by DustinCampbell** [comment]
> Is this TextMate gammar is currently ships with Visual Studio Code?

Yes. This is the official TextMate grammar from the C# team.

> I'm making a theme, is there a documentation / list for all the scopes?
> Or a default theme that uses all these scopes?

Try the Dark+ (default dark) theme in VS Code. We've tried to be careful to match the same scopes that the TypeScript grammar provides.

> Does OmniSharp have any additional syntax highlighting method?
> Something that uses code inspection instead regular expression matching.
> That could differentiate e.g. a namespace from a class even if they have the same name.

Sort of. OmniSharp uses Roslyn, which provides the same API to classify tokens that is used in Visual Studio. What you've described is _semantic_ highlighting, which Roslyn certainly supports and OmniSharp can expose. However, there is no API in VS Code to provide semantic highlighting today. https://github.com/Microsoft/vscode/issues/585 tracks this API for VS Code.


Does that answer your questions?

**Comment by eppz** [comment]
Wow, thanks!
It is way more detailed answer than expected. 😃 

I was hoping that Language Server Protocol - https://github.com/Microsoft/language-server-protocol, https://github.com/Microsoft/vscode-languageserver-node - somewhat enables VS Code to do semantic coloring somehow. Should I forget about it?

**Comment by DustinCampbell** [comment]
Unfortunately, the language server protocol doesn't not have an end point for coloring that I'm aware of.

**Comment by eppz** [comment]
Thanks again!

**Comment by DustinCampbell** [comment]
Not a problem. Let me know if you have any other questions.

**Comment by eppz** [comment]
Managed to extend official C# grammar (reusing "base" rules), with a quirky workaround. It features some basic Unity specific keyword / class lookup (to mimic some semantic highlighting). 

The resulting theme is at https://marketplace.visualstudio.com/items?itemName=eppz.eppz-code
