### ISSUE TITLE
Variable changing color when using accessor

### ISSUE THREAD

**Issue by rphlmr** [dotnet/csharp-tmLanguage#58]
Primarily open on VSCode issue tracker but maybe it's a better place here. (https://github.com/Microsoft/vscode/issues/24827)
With my theme (visual-gruvbox-medium-dark) or other themes.

One color is defined for "keyword.type.cs" (exemple : blue)
One color is defined for "entity.name.variable.local.cs" (exemple : beige)
One color is defined for "variable.other.object.cs" (exemple : green.)

When i use a variable previously defined as "keyword.type.cs" or "entity.name.variable.local.cs" with the dot accessor ("punctuation.accessor.cs"), it is muted on "variable.other.object.cs" (and the color change, of course).

For a code color coherence, we need to keep the color defined on the variable declaration. The variable must don't mute into "variable.other.object.cs" and keeps it color.
The regex should (is it possible ?) keep the previous type assigne to the variable.

<img width="819" alt="0a62ae86-2203-11e7-87f8-1ba6aa063455" src="https://cloud.githubusercontent.com/assets/20722140/25100600/015f9e16-23b1-11e7-9a62-9b0a63efd48b.png">

**Comment by DustinCampbell** [comment]
There's nothing we can do about `helper.Help();` in a TextMate grammar. However, `string.Equals("a", "b'');` should have `string` colored as a keyword. That issue is tracked with https://github.com/dotnet/csharp-tmLanguage/issues/19.
