### ISSUE TITLE
Nullable + tuple ==> wrong colorization

### ISSUE THREAD

**Issue by ljw1004** [dotnet/csharp-tmLanguage#59]
Almost all the colorization in this snippet is incorrect!

![image](https://cloud.githubusercontent.com/assets/3316258/25404629/8f01e8dc-29b5-11e7-89ab-f4dd71817fcf.png)

Here's how it should properly look:

![image](https://cloud.githubusercontent.com/assets/3316258/25404958/89a99604-29b6-11e7-9b96-83910bf09f99.png)

As far as I can tell, the colorizer kind of loses the plot because of the combination of tuples and nullable -- changing the return type to either of `(double weight, int n)` or to `double?` fixes it.

*In VSCode 1.11.2, last updated April 25th, using the built in `Light+ (default light)` theme.*

**Comment by DustinCampbell** [comment]
Thanks Lucian!

**Comment by DustinCampbell** [comment]
Thanks for the help here @kiootic!

**Comment by ljw1004** [comment]
@kiootic nice work. Those grammar files look really tough to work on.

**Comment by DustinCampbell** [comment]
Changing the type name match is really the trickiest part of the grammar. I'm _very_ happy to have not been the one updating them this time. :smile:
