### ISSUE TITLE
Can't colorize correct, because tokens have a same type

### ISSUE THREAD

**Issue by yolorusher** [dotnet/csharp-tmLanguage#71]
## Details

Local variables, static classes, enums has the same type
Generic Interfaces and Classes has the same type
I can't colorize it correct

## Repro
https://github.com/yolorusher/csharp-tmLanguage-issue
<img width="464" alt="problems" src="https://user-images.githubusercontent.com/19669946/27125227-4b55a1d2-50fc-11e7-96ae-b776c38d05e6.png">
Definition colors is correct
<img width="272" alt="definitions" src="https://user-images.githubusercontent.com/19669946/27125246-596069a6-50fc-11e7-85b1-702b05007f17.png">

Same thing with interfaces
![image](https://user-images.githubusercontent.com/19669946/27125740-f0d4aae4-50fd-11e7-8b62-2ebdb29c54cd.png)

**Comment by DustinCampbell** [comment]
Unfortunately, there's not much we can do about this at the moment. C# for VS Code has all of the information needed to properly perform semantic highlighting. However, highlighting in VS Code is handled by scanning each line with regular expressions. Hopefully, VS Code will supply an API that will allow us to provide semantic highlights as well. https://github.com/Microsoft/vscode/issues/585 tracks this on the VS Code repo.
