### ISSUE TITLE
Local functions type

### ISSUE THREAD

**Issue by yolorusher** [dotnet/csharp-tmLanguage#73]
## Details

Why local functions has a readwrite type?

## Repro
https://github.com/yolorusher/csharp-tmLanguage-issue2
![image](https://user-images.githubusercontent.com/19669946/27127317-2d72df16-5103-11e7-832e-a6ea0b6e96e4.png)

Please provide a code example and (optionally) a screenshot demonstrating the problem.

**Comment by DustinCampbell** [comment]
Thanks for the report! C# 7 Local Functions are not implemented yet in the C# TextMate grammar. We're tracking this with https://github.com/dotnet/csharp-tmLanguage/issues/10.
