### ISSUE TITLE
Type constraint causes method body to be highlighted as a type

### ISSUE THREAD

**Issue by andy-hanson** [dotnet/csharp-tmLanguage#74]
## Details

What editor are you seeing the problem in? VSCode

What version of the editor are you using? 1.14.0-Insider

What color theme are you using? Light+ (default light)

## Repro

```cs
T id1<T>(T a) => a;
T id2<T>(T a) where T : class => a;
```

![shot](https://user-images.githubusercontent.com/5387404/27209588-8ce85bfc-5201-11e7-8462-05ba65734f0d.jpg)

**Comment by DustinCampbell** [comment]
Thanks for the report!
