### ISSUE TITLE
"enum" in in-line comment breaks syntax highlighting

### ISSUE THREAD

**Issue by kameko** [dotnet/csharp-tmLanguage#75]
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
Visual Studio Code

What version of the editor are you using?
1.13.1

What color theme are you using?
Default

## Repro

Please provide a code example and (optionally) a screenshot demonstrating the problem.
Using the word "enum" within an in-line comment (a comment on a line of code) break all syntax highlighting after that comment
![image](http://i.imgur.com/hMvllLx.png)

**Comment by DustinCampbell** [comment]
Good bug. Thanks!

**Comment by kameko** [comment]
I've just realized it does the same thing with "class", it probably happens with all type-specifying keywords.

**Comment by DustinCampbell** [comment]
Yes, that's correct.
