### ISSUE TITLE
Lambda with multiple argument causes tuple to the left of it to have no highlighting

### ISSUE THREAD

**Issue by andy-hanson** [dotnet/csharp-tmLanguage#77]
## Details

What editor are you seeing the problem in? VSCode

What version of the editor are you using? 1.14.0-Insider

What color theme are you using? Light+ (default light)

## Repro

```cs
IEnumerable<string> foo(params (string, string)[] args) => args.Select(a => a.Item1);
IEnumerable<string> bar() => foo(("a", "b")).Select((item, index) => item);
```
![shot](https://user-images.githubusercontent.com/5387404/27773939-d3befae0-5f3a-11e7-928c-bfd04611df7b.jpg)

I expected `"a", "b"` to be highlighted as strings.

**Comment by DustinCampbell** [comment]
Thanks for the report!

**Comment by DustinCampbell** [comment]
The issue here is that the regex rule for a lambda expression with multiple parameters is too permissive. Essentially, it looks for a start parenthesis followed by any characters up to a closing parenthesis and an arrow. So, it ends up matching the start of the tuple literal all the way up to the arrow and treating that whole span of text as a lambda expression.

**Comment by wise0704** [comment]
> The issue here is that the regex rule for a lambda expression with multiple parameters is too permissive. Essentially, it looks for a start parenthesis followed by any characters up to a closing parenthesis and an arrow. So, it ends up matching the start of the tuple literal all the way up to the arrow and treating that whole span of text as a lambda expression.

Lambda detection should probably start with `=>` instead of from the parameter parentheses. Params should just be highlighted as a tuple.

What would be affected:
```c#
(int a, int b) x = ...
// instead of trying to mark x as "local",
// just let it mark it as "readwrite" after consuming (int a, int b) as a tuple

(a, b) => ...
// a and b would be marked as readwrite instead of parameters

(int, String) y = ...
// int would be marked keyword, but String would be marked readwrite
// - job for semantic highlighting to override
```

But it would also help solve the multiline issue:
```c#
(
    int a,
    List<string> b,
) =>
{ ... }
```
since `( )` is then just a comma-separated collection of expressions.
