### ISSUE TITLE
C# highlight 'namespace' and 'class' in different color

### ISSUE THREAD

**Issue by aeschli** [dotnet/csharp-tmLanguage#87]
_From @klirium on November 17, 2017 11:5_

Suppose we have this code:
```cs
using System;
using System.Collections.Generic;

namespace ConsoleApp {
    class Program {
        static void Main (string[] args) {
            System.Collections.Generic.List<string> list = new List<string> ();
        }
    }
}
```
in the text editor when we type **System.Collections.Generic.List**, we actually have two types of entities in one statement: **System.Collections.Generic** - is a namespace, and **List** - is a class. It would be nice to have ability to distinguish this two types via color highlighting. For example in Visual Studio we can highlight System.Collections.Generic in black and List in strong purple. Even more having Resharper installed and **using System.Collections.Generic;** statement at the top of the file, it could be marked as redundant and removed via refactor tools. But in VS Code if we call "Developer: Inspect TM Scopes" it will show us that these two entities have the same types:
- storage.type.cs
- regions.namespace.cs.extensions
- source.cs

_Copied from original issue: Microsoft/vscode#38610_

**Comment by DustinCampbell** [comment]
Unfortunately, highlighting in VS Code is handled via regular expressions. We're unable to use the semantics of the C# language to provide custom highlights for different symbols, like types and namespaces. Hopefully, VS Code will add an API in the future to support this. https://github.com/Microsoft/vscode/issues/585 is tracking this issue.

Note: `regions.namespace.cs.extensions` looks like a scope produced by a different extension. It isn't produced by C# for VS Code or the C# TextMate grammar.

**Comment by wise0704** [comment]
Handled by semantic highlighting:

![image](https://github.com/dotnet/csharp-tmLanguage/assets/13545633/2b7676f6-1166-4f3d-9dd0-9fc164936a61)

Impossible for textmate because left of dot could still be a type:

![image](https://github.com/dotnet/csharp-tmLanguage/assets/13545633/cf823672-5651-4af1-8958-6704ed9839b0)

Weird to say but this is both fixed and can't be fixed.
