### ISSUE TITLE
C# highlighting ref when part of variable name in lambda expression

### ISSUE THREAD

**Issue by watkinsmatthewp** [dotnet/csharp-tmLanguage#95]
(Originally reported in https://github.com/Microsoft/vscode/issues/40911)

## Details

VSCode Version: Code 1.19.1 (0759f77, 2017-12-19T09:46:23.884Z)
Color theme: Dark (Visual Studio)

## Repro

Enter the following lines in a C# file:

```cs
var refObjectsToKeep = allRefObjects.Where(refObject => refObject.ShouldKeep);
var intObjectsToKeep = allIntObjects.Where(intObject => intObject.ShouldKeep);
var outObjectsToKeep = allOutObjects.Where(outObject => outObject.ShouldKeep);
```

Notice the incorrectly highlighted "ref" in "refObject":

![image](https://user-images.githubusercontent.com/3808901/34418970-0bab9942-ebcf-11e7-919f-4e1d978053c9.png)

Looks like ref is the only reserved word that shows this behavior.

**Comment by DustinCampbell** [comment]
Thanks! Looks like the problem is [here](https://github.com/dotnet/csharp-tmLanguage/blob/master/src/csharp.tmLanguage.yml#L2383-L2385). The regex matches `ref` without `\b` on either side.
