### ISSUE TITLE
C# syntax highlight: star (multiplication) in function-call mistakenly highlighted

### ISSUE THREAD

**Issue by aeschli** [dotnet/csharp-tmLanguage#99]
_From @CCludts on February 13, 2018 22:20_

- VSCode Version: 1.20.0
- OS Version: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592). Windows10 Pro 64x

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/18717967/36176920-73c4ad88-1114-11e8-9fc3-475cfb4dc975.png)

1. Any file with c# language-mode  (new Untitled file works, saving is irrelevant)
2. `Multiply(n1 * n2);`

Does this issue occur when all extensions are disabled?: __Yes__

edit: this issue already existed on the previous release of VSCode

_Copied from original issue: Microsoft/vscode#43621_

**Comment by CCludts** [comment]
![image](https://user-images.githubusercontent.com/18717967/36343186-4e0c48ba-1409-11e8-8a8f-fc88452dc155.png)
Also shows up in for loops

**Comment by michaelblyons** [comment]
Looks like the `int i` part of the loops has different scope names as well.

**Comment by DustinCampbell** [comment]
It looks to me like a bug with identifying pointer types.

**Comment by DustinCampbell** [comment]
since syntax highlighting is achieved with regular expressions, that's particularly tricky.

**Comment by DustinCampbell** [comment]
This should be fixed now. We've decided to prefer multiplication over pointer types.
